apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: mizline
data:
  POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
