apiVersion: v1
kind: Service
metadata:
  name: kitchen
  labels:
    app.kubernetes.io/name: kitchen
    app.kubernetes.io/part-of: mizline
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: kitchen
  ports:
    - name: http
      port: 3001
      targetPort: http
