apiVersion: v1
kind: ConfigMap
metadata:
  name: mizline-config
  labels:
    app.kubernetes.io/part-of: mizline
data:
  CORS_ORIGINS: "http://order.mizline.local,http://kitchen.mizline.local"
  API_HOST: "api.mizline.local"
  CUSTOMER_HOST: "order.mizline.local"
  KITCHEN_HOST: "kitchen.mizline.local"
