apiVersion: v1
kind: ConfigMap
metadata:
  name: mizline-config
  labels:
    app.kubernetes.io/part-of: mizline
data:
  CORS_ORIGINS: "http://app.mizline.local,http://order.mizline.local"
  API_HOST: "api.mizline.local"
  SITE_HOST: "app.mizline.local"
