apiVersion: v1
kind: Service
metadata:
  name: customer
  labels:
    app.kubernetes.io/name: customer
    app.kubernetes.io/part-of: mizline
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: customer
  ports:
    - name: http
      port: 3000
      targetPort: http
