apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: mizline
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mizline-local
  resources:
    requests:
      storage: 2Gi
