apiVersion: v1
kind: PersistentVolume
metadata:
  name: mizline-redis-pv
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: mizline
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mizline-local
  hostPath:
    path: /data/mizline/redis
    type: DirectoryOrCreate
